### ISSUE TITLE
s2i/run attempts to source missing scl-enable-maven

### ISSUE THREAD

**Issue by jmtd** [jboss-openshift/cct_module#354]
With the OpenJDK RHEL8/JDK11 image, on start up, one gets the following error

```
/usr/local/s2i/run: line 15: /opt/jboss/container/maven/default//scl-enable-maven: No such file or directory

```

The image uses the following modules at the top level (image):

```
  install:
  - name: jboss.container.openjdk.jdk
    version: "8"
  - name: jboss.container.java.s2i.bash
  - name: jboss.container.openjdk.jdk
    version: "11"
  - name: jboss.container.maven.35.bash
    version: "3.5"
```
Cekit (3.4.0) unravels this to the following full list

```
jboss.container.java.jvm.api     jboss.container.maven.35.bash       jboss.container.prometheus.bash
jboss.container.java.jvm.bash    jboss.container.maven.api           jboss.container.proxy.api
jboss.container.java.proxy.bash  jboss.container.maven.default.bash  jboss.container.s2i.core.api
jboss.container.java.run.bash    jboss.container.maven.s2i.api       jboss.container.s2i.core.bash
jboss.container.java.s2i.bash    jboss.container.maven.s2i.bash      jboss.container.user
jboss.container.jolokia.api      jboss.container.openjdk.jdk         jboss.container.util.logging.bash
jboss.container.jolokia.bash     jboss.container.prometheus.api
```

the script `jboss/container/java/s2i/bash/artifacts/usr/local/s2i/run` contains the following

```
# XXX: Not sure why we need to setup maven, but this was part of the old s2i-setup script, so...
source "${JBOSS_CONTAINER_MAVEN_DEFAULT_MODULE}/scl-enable-maven"
```

(that comment looks suspicious)

the var JBOSS_CONTAINER_MAVEN_DEFAULT_MODULE is not set in that script. It's defined as set in `jboss/container/maven/default/bash/module.yaml`, but I can't see where it's actually set. Based on the error above it must be being set to `/opt/jboss/container/maven/default/` by something.
